php:
  image: php:7.1-fpm
  container_name: frontPhp
  volumes:
    - ./files:/var/www/core-front-app
  ports:
   - 9000:9000

nginx:
  image: nginx:1.10.3
  container_name: frontNginx
  volumes_from:
    - php
  volumes:
    - ./docker-conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    -  8080:80
